package com.sm.android.countries.cities.utils

object Keys {
    const val IS_LOCATION_PERMISSION_DENIED = "IS_LOCATION_PERMISSION_DENIED"
    const val LOCATION_DETAILS = "LOCATION_DETAILS"
    const val CITY_NAME = "CITY_NAME"
    const val DEFAULT_APP_LANGUAGE = "DEFAULT_APP_LANGUAGE"
    const val IS_APP_LANGUAGE_SELECTED = "IS_APP_LANGUAGE_SELECTED"
    const val APP_LANGUAGE = "APP_LANGUAGE"
    const val IS_FIRST_TIME = "IS_FIRST_TIME"
    const val HIJRI_CORRECTION = "HIJRI_CORRECTION"
    const val IS_RAMADAN_STARTED = "IS_RAMADAN_STARTED"
    const val TIMINGS = "TIMINGS"
    const val LANGUAGE_KEY = "LANGUAGE_KEY"

    const val LOCATION_METHOD = "location_method"
    const val LOCATION_METHOD_AUTO = "location_method_automatic"
    const val LOCATION_METHOD_MANUAL = "location_method_manual"
    const val LATITUDE = "latitude"
    const val LONGITUDE = "longitude"
    const val COUNTRY = "country"
    const val COUNTRY_ID = "country_id"
    const val CITY = "city"
    const val CITY_ID = "city_id"
    const val STATE = "state"
    const val STATE_ID = "state_id"
    const val PRAYER_REMINDER = "prayer_reminder"
    const val TWELVE_TIME_FORMAT = "twelve_time_format"
    const val IS_WORKER_SET = "IS_WORKER_SET"
    const val SELECTED_COMPASS_KEY = "SELECTED_COMPASS_KEY"
    const val QIBLA_SELECTED_COMPASS_BACKGROUND = "QIBLA_SELECTED_COMPASS_BACKGROUND"
    const val QIBLA_SELECTED_COMPASS_DIRECTION = "QIBLA_SELECTED_COMPASS_DIRECTION"
    const val FONT_SIZE = "FONT_SIZE"
    const val QURAN_TRANSLATION_KEY = "QURAN_TRANSLATION_KEY"
    const val QURAN_LAST_RAED = "QURAN_LAST_RAED"
    const val PRIVACY_POLICY_CHECK = "PRIVACY_POLICY_CHECK"
    const val CURRENT_PRAYER_URI = "CURRENT_PRAYER_URI"
    const val SELECTED_AZAAN = "SELECTED_AZAAN"

}